version: '3.9'
services:      
  temp-redis-master:
    hostname: temp-redis-master
    container_name: temp-redis-master
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    
    network_mode: host 

    ports:
      - 6974:6379

  # slave1 : bitnami/redis:6.2.6
  temp-redis-slave-1:
    hostname: temp-redis-slave-1
    container_name: temp-redis-slave-1
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=temp-redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6975:6379
    network_mode: host 
    depends_on:
      - temp-redis-master

  # slave2 : bitnami/redis:6.2.6
  temp-redis-slave-2:
    hostname: temp-redis-slave-2
    container_name: temp-redis-slave-2
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=temp-redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6976:6379
    network_mode: host 
    depends_on:
      - temp-redis-master
      - temp-redis-slave-1


  # sentinel1 : bitnami/redis-sentinel:6.2.6
  temp-redis-sentinel-1:
    hostname: temp-redis-sentinel-1
    container_name: temp-redis-sentinel-1
    image: bitnami/redis-sentinel:6.2.6
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=60000
      - REDIS_MASTER_HOST=temp-redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=temp-master-name
      - REDIS_SENTINEL_QUORUM=2
      # - REDIS_SENTINEL_PASSWORD=170anwkd!
    depends_on:
      - temp-redis-master
      - temp-redis-slave-1
      - temp-redis-slave-2
      - temp-redis-slave-3
    ports:
      - 28575:26379
    network_mode: host 

  temp-redis-sentinel-2:
    hostname: temp-redis-sentinel-2
    container_name: temp-redis-sentinel-2
    image: bitnami/redis-sentinel:6.2.6
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=60000
      - REDIS_MASTER_HOST=temp-redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=temp-master-name
      - REDIS_SENTINEL_QUORUM=2
      # - REDIS_SENTINEL_PASSWORD=170anwkd!
    depends_on:
      - temp-redis-master
      - temp-redis-slave-1
      - temp-redis-slave-2
      - temp-redis-slave-3
    network_mode: host 
    ports:
      - 28576:26379

  # sentinel3 : bitnami/redis-sentinel:6.2.6
  temp-redis-sentinel-3:
    hostname: temp-redis-sentinel-3
    container_name: temp-redis-sentinel-3
    image: bitnami/redis-sentinel:6.2.6
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=60000
      - REDIS_MASTER_HOST=temp-redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=temp-master-name
      - REDIS_SENTINEL_QUORUM=2
      # - REDIS_SENTINEL_PASSWORD=170anwkd!
    depends_on:
      - temp-redis-master
      - temp-redis-slave-1
      - temp-redis-slave-2
      - temp-redis-slave-3
    ports:
      - 28577:26379
    network_mode: host 