# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_test
    restart: unless-stopped
    environment:
      MYSQL_USER: junmo
      MYSQL_PASSWORD: wnsah12
      MYSQL_ROOT_PASSWORD: wnsah12
      MYSQL_DATABASE: mysql_test_db
    ports:
      - 3300:3306
    volumes:
      - ./mysql/data/:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci