version: '3.9'
services:
  jmshop_mariadb:
    container_name: wifiservice_mariadb
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3304:3306
    volumes:
      - ./mariadb/data/:/var/lib/mysql
    environment:
      MARIADB_USER: junmokang
      MARIADB_PASSWORD: wnsah12
      MARIADB_ROOT_PASSWORD: wnsah12
      MARIADB_DATABASE: wifiservice_mariadb

