version: '3.9'
services:
  jmblog_mariadb:
    container_name: jmblog_mariadb
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3303:3306
    volumes:
      - ./mariadb/data/:/var/lib/mysql
    environment:
      MARIADB_USER: junmokang
      MARIADB_PASSWORD: wnsah12
      MARIADB_ROOT_PASSWORD: wnsah12
      MARIADB_DATABASE: jmblog_mariadb
  
  jmblog_redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    container_name: jmblog_redis
    command: redis-server /usr/local/conf/redis.conf
    hostname: jmblog_redis 
    volumes:
      - ./redis/data/:/data
      - ./redis/redis.conf:/usr/local/conf/redis.conf

  jmblog_redis-stat:
    image: insready/redis-stat:latest
    ports:
      - 8479:63790
    restart: unless-stopped
    container_name: jmblog_redis-stat
    links:
      - jmblog_redis:jmblog_redis
    command: --server jmblog_redis
    depends_on:
      - jmblog_redis