version: '3.9'
services:      
  jmblog_mariadb_master:
    build: 
      context: ./
      dockerfile: mariadb/master/Dockerfile
    restart: unless-stopped
    environment:
      MARIADB_USER: junmokang
      MARIADB_PASSWORD: wnsah12
      MARIADB_ROOT_PASSWORD: wnsah12
      MARIADB_DATABASE: jmblog_mariadb
    ports:
      - 3310:3306
    # Where our data will be persisted
    volumes:
      - ./mariadb/master/data/:/var/lib/mysql
    networks:
      net-mysql:
        ipv4_address: 172.26.0.10
  
  jmblog_mariadb_slave:
    build: 
      context: ./
      dockerfile: mariadb/slave/Dockerfile
    restart: unless-stopped
    environment:
      MARIADB_USER: junmokang
      MARIADB_PASSWORD: wnsah12
      MARIADB_ROOT_PASSWORD: wnsah12
      MARIADB_DATABASE: jmblog_mariadb
    ports:
      - 3311:3306
    # Where our data will be persisted
    volumes:
      - ./mariadb/slave/data/:/var/lib/mysql
    networks:
      net-mysql:
        ipv4_address: 172.26.0.11

  # redis-stat:
  #   image: insready/redis-stat:latest
  #   ports:
  #     - 8479:63790
  #   restart: unless-stopped
  #   container_name: redis-master
  #   links:
  #     - redis-master:redis-master
  #   command: --server redis-master
  #   depends_on:
  #     - redis-master

  redis-master:
    hostname: redis-master
    container_name: redis-master
    image: redis:latest
    restart: unless-stopped
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/data/:/data
      - ./redis/redis.conf:/usr/local/conf/redis.conf
    networks:
      - net-redis
    ports:
      - 6379:6379

  redis_stat:
    image: insready/redis-stat:latest
    ports:
      - 6480:63790
    restart: unless-stopped
    container_name: redis_stat
    links:
      - redis-master:redis-master
    command: --server redis-master
    networks:
      - net-redis
    depends_on:
      - redis-master

  
networks: 
  net-mysql:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
  net-redis:
    driver: bridge