version: '3.9'
services:      
  jmblog_mariadb_master:
    build: 
      context: ./
      dockerfile: mariadb/master/Dockerfile
    restart: unless-stopped
    environment:
      MARIADB_USER: junmokang
      MARIADB_PASSWORD: wnsah12
      MARIADB_ROOT_PASSWORD: wnsah12
      MARIADB_DATABASE: jmblog_mariadb
    ports:
      - 3310:3306
    # Where our data will be persisted
    volumes:
      - ./mariadb/master/data/:/var/lib/mysql
    networks:
      net-mysql:
        ipv4_address: 172.26.0.10
  
  jmblog_mariadb_slave:
    build: 
      context: ./
      dockerfile: mariadb/slave/Dockerfile
    restart: unless-stopped
    environment:
      MARIADB_USER: junmokang
      MARIADB_PASSWORD: wnsah12
      MARIADB_ROOT_PASSWORD: wnsah12
      MARIADB_DATABASE: jmblog_mariadb
    ports:
      - 3311:3306
    # Where our data will be persisted
    volumes:
      - ./mariadb/slave/data/:/var/lib/mysql
    networks:
      net-mysql:
        ipv4_address: 172.26.0.11

  # redis-stat:
  #   image: insready/redis-stat:latest
  #   ports:
  #     - 8479:63790
  #   restart: unless-stopped
  #   container_name: redis-master
  #   links:
  #     - redis-master:redis-master
  #   command: --server redis-master
  #   depends_on:
  #     - redis-master

  redis-master:
    hostname: redis-master
    container_name: redis-master
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./master/backup:/freelog/backup
    
    networks:
      - net-redis
    ports:
      - 6379:6379

  # slave1 : bitnami/redis:6.2.6
  redis-slave-1:
    hostname: redis-slave-1
    container_name: redis-slave-1
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6480:6379
    volumes:
      - ./slave1/backup:/freelog/backup
    networks:
      - net-redis
    depends_on:
      - redis-master

  # slave2 : bitnami/redis:6.2.6
  redis-slave-2:
    hostname: redis-slave-2
    container_name: redis-slave-2
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6481:6379
    networks:
      - net-redis
    volumes:
      - ./slave2/backup:/freelog/backup
    depends_on:
      - redis-master
      - redis-slave-1


  # slave3 : bitnami/redis:6.2.6
  redis-slave-3:
    hostname: redis-slave-3
    container_name: redis-slave-3
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6482:6379
    volumes:
      - ./slave3/backup:/freelog/backup
    networks:
      - net-redis
    depends_on:
      - redis-master
      - redis-slave-2

  # sentinel1 : bitnami/redis-sentinel:6.2.6
  redis-sentinel-1:
    hostname: redis-sentinel-1
    container_name: redis-sentinel-1
    image: bitnami/redis-sentinel:6.2.6
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=60000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=master-name
      - REDIS_SENTINEL_QUORUM=2
      # - REDIS_SENTINEL_PASSWORD=170anwkd!
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3
    ports:
      - 26379:26379
    networks:
      - net-redis
    volumes:
      - ./sentinel1/backup:/freelog/backup

  redis-sentinel-2:
    hostname: redis-sentinel-2
    container_name: redis-sentinel-2
    image: bitnami/redis-sentinel:6.2.6
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=60000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=master-name
      - REDIS_SENTINEL_QUORUM=2
      # - REDIS_SENTINEL_PASSWORD=170anwkd!
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3
    ports:
      - 26380:26379
    networks:
      - net-redis
    volumes:
      - ./sentinel2/backup:/freelog/backup

  # sentinel3 : bitnami/redis-sentinel:6.2.6
  redis-sentinel-3:
    hostname: redis-sentinel-3
    container_name: redis-sentinel-3
    image: bitnami/redis-sentinel:6.2.6
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=60000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=master-name
      - REDIS_SENTINEL_QUORUM=2
      # - REDIS_SENTINEL_PASSWORD=170anwkd!
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3
    ports:
      - 26381:26379
    networks:
      - net-redis
    volumes:
      - ./sentinel3/backup:/freelog/backup

  
networks: 
  net-mysql:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
  net-redis:
    driver: bridge